export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import "./global.css";
import LogoutButton from "@/components/LogoutButton";
import LoginButton from "@/components/LoginButton";
import {
  AppBar,
  Box,
  Toolbar,
  IconButton,
  Typography,
  Button,
} from "@mui/material";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Box sx={{ flexGrow: 1 }}>
          <AppBar position="static">
            <Toolbar>
              <IconButton
                size="large"
                edge="start"
                color="inherit"
                aria-label="menu"
                sx={{ mr: 2 }}
              ></IconButton>
              <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
                News
              </Typography>
              <LogoutButton />
              <LoginButton />
            </Toolbar>
          </AppBar>
        </Box>

        <div className="container">{children}</div>
      </body>
    </html>
  );
}
